<a href="https://colab.research.google.com/github/MishaR950/Hack/blob/main/Hack.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
import pandas as pd

train = pd.read_csv('/content/credit_score_ds.csv')
train.head(3)

  month|age|occupation|annual_income|monthly_inhand_salary|num_bank_accounts|num_credit_card|num_of_loan|num_credit_inquiries|credit_history_age|amount_invested_monthly|payment_behaviour|monthly_balance|credit_score
0  1|23.0|Scientist|19114.12|1824.8433333333328|3...
1  2|23.0|Scientist|19114.12|1824.8433333333328|3...
2  3|23.0|Scientist|19114.12|1824.8433333333328|3...

In [29]:
# import pandas as pd
# import numpy as np

from sklearn.metrics import roc_curve, auc
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.decomposition import PCA

import string, re, pylab as pl

# SampleCustomers = pd.read_csv('/content/credit_score_ds.csv',';')
# SampleAccounts = pd.read_csv('/content/credit_score_ds.csv',';', decimal=',')
# SampleAccounts.head()

In [15]:
df

      month|age|occupation|annual_income|monthly_inhand_salary|num_bank_accounts|num_credit_card|num_of_loan|num_credit_inquiries|credit_history_age|amount_invested_monthly|payment_behaviour|monthly_balance|credit_score
0      1|23.0|Scientist|19114.12|1824.8433333333328|3...
1      2|23.0|Scientist|19114.12|1824.8433333333328|3...
2      3|23.0|Scientist|19114.12|1824.8433333333328|3...
3      4|23.0|Scientist|19114.12|1824.8433333333328|3...
4      5|23.0|Scientist|19114.12|1824.8433333333328|3...
...                                                  ...
99995  4|25.0|Mechanic|39628.99|3359.415833333333|4.0...
99996  5|25.0|Mechanic|39628.99|3359.415833333333|4.0...
99997  6|25.0|Mechanic|39628.99|3359.415833333333|4.0...
99998  7|25.0|Mechanic|39628.99|3359.415833333333|4.0...
99999  8|25.0|Mechanic|39628.99|3359.415833333333|4.0...

[100000 rows x 1 columns]

No charts were generated by quickchart

In [8]:
df = pd.read_csv('/content/credit_score_df.csv', sep = '|')

In [17]:
df

,month,age,occupation,annual_income,monthly_inhand_salary,num_bank_accounts,num_credit_card,num_of_loan,num_credit_inquiries,credit_history_age,amount_invested_monthly,payment_behaviour,monthly_balance,credit_score
0,1,23.0,Scientist,19114.12,1824.843333,3.0,4.0,4.0,4.0,265.0,21.465380,High_spent_Small_value_payments,312.494089,0
1,2,23.0,Scientist,19114.12,1824.843333,3.0,4.0,4.0,4.0,266.0,21.465380,Low_spent_Large_value_payments,284.629162,0
2,3,23.0,Scientist,19114.12,1824.843333,3.0,4.0,4.0,4.0,267.0,21.465380,Low_spent_Medium_value_payments,331.209863,0
3,4,23.0,Scientist,19114.12,1824.843333,3.0,4.0,4.0,4.0,268.0,21.465380,Low_spent_Small_value_payments,223.451310,0
4,5,23.0,Scientist,19114.12,1824.843333,3.0,4.0,4.0,4.0,269.0,21.465380,High_spent_Medium_value_payments,341.489231,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,4,25.0,Mechanic,39628.99,3359.415833,4.0,6.0,2.0,3.0,378.0,24.028477,High_spent_Large_value_payments,479.866228,1
99996,5,25.0,Mechanic,39628.99,3359.415833,4.0,6.0,2.0,3.0,379.0,24.028477,High_spent_Medium_value_payments,496.651610,1
99997,6,25.0,Mechanic,39628.99,3359.415833,4.0,6.0,2.0,3.0,380.0,24.028477,High_spent_Large_value_payments,516.809083,1
99998,7,25.0,Mechanic,39628.99,3359.415833,4.0,6.0,2.0,3.0,381.0,24.028477,Low_spent_Large_value_payments,319.164979,0
99999,8,25.0,Mechanic,39628.99,3359.415833,4.0,6.0,2.0,3.0,382.0,24.028477,Low_spent_Medium_value_payments,393.673696,1

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 14 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   month                    100000 non-null  int64
 1   age                      100000 non-null  float64
 2   occupation               100000 non-null  object
 3   annual_income            100000 non-null  float64
 4   monthly_inhand_salary    100000 non-null  float64
 5   num_bank_accounts        100000 non-null  float64
 6   num_credit_card          100000 non-null  float64
 7   num_of_loan              100000 non-null  float64
 8   num_credit_inquiries     100000 non-null  float64
 9   credit_history_age       100000 non-null  float64
 10  amount_invested_monthly  100000 non-null  float64
 11  payment_behaviour        100000 non-null  object
 12  monthly_balance          100000 non-null  float64
 13  credit_score             100000 non-null  int64
dtypes: float64(10), int64(2), object(2)
memory usage: 10.7+ MB

In [6]:
# import pandas as pd
# from sklearn.preprocessing import OneHotEncoder

# # Предположим, что df - это ваш исходный DataFrame, и 'occupation' - это колонка для кодирования.
# df_onehot = df.copy()

# # Создаем экземпляр OneHotEncoder с параметром drop='first'
# onehotencoder = OneHotEncoder(drop='first', sparse=False)

# # Проводим one-hot кодирование, исключая первый признак, и создаем новый DataFrame
# encoded_occupation = pd.DataFrame(onehotencoder.fit_transform(df_onehot[['occupation']]))

# # Получаем новые имена для one-hot закодированных колонок, исключая первый признак
# encoded_occupation.columns = onehotencoder.get_feature_names_out(['occupation'])

# # Присоединяем закодированный DataFrame к исходному
# df_onehot = df_onehot.join(encoded_occupation)

# # Удаляем исходную колонку 'occupation'
# df_onehot.drop('occupation', axis=1, inplace=True)

# # Теперь df_onehot содержит закодированные признаки вместо исходной колонки 'occupation'
# df_onehot

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(

,month,age,annual_income,monthly_inhand_salary,num_bank_accounts,num_credit_card,num_of_loan,num_credit_inquiries,credit_history_age,amount_invested_monthly,...,occupation_Entrepreneur,occupation_Journalist,occupation_Lawyer,occupation_Manager,occupation_Mechanic,occupation_Media_Manager,occupation_Musician,occupation_Scientist,occupation_Teacher,occupation_Writer
0,1,23.0,19114.12,1824.843333,3.0,4.0,4.0,4.0,265.0,21.465380,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
1,2,23.0,19114.12,1824.843333,3.0,4.0,4.0,4.0,266.0,21.465380,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
2,3,23.0,19114.12,1824.843333,3.0,4.0,4.0,4.0,267.0,21.465380,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
3,4,23.0,19114.12,1824.843333,3.0,4.0,4.0,4.0,268.0,21.465380,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
4,5,23.0,19114.12,1824.843333,3.0,4.0,4.0,4.0,269.0,21.465380,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,4,25.0,39628.99,3359.415833,4.0,6.0,2.0,3.0,378.0,24.028477,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
99996,5,25.0,39628.99,3359.415833,4.0,6.0,2.0,3.0,379.0,24.028477,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
99997,6,25.0,39628.99,3359.415833,4.0,6.0,2.0,3.0,380.0,24.028477,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
99998,7,25.0,39628.99,3359.415833,4.0,6.0,2.0,3.0,381.0,24.028477,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
99999,8,25.0,39628.99,3359.415833,4.0,6.0,2.0,3.0,382.0,24.028477,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0

Warning: Total number of columns (27) exceeds max_columns (20) limiting to first (20) columns.
Warning: total number of rows (100000) exceeds max_rows (20000). Limiting to first (20000) rows.

In [37]:
from sklearn.linear_model import LogisticRegressionCV
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler
import numpy as np

# Предположим, что df уже определён и содержит необходимые данные
df = pd.get_dummies(df)  # преобразовываем все категориальные переменные
scaler = StandardScaler()

# Теперь мы предполагаем, что все переменные в df, кроме 'credit_score', являются числовыми.
X = df.drop('credit_score', axis=1)
y = df['credit_score']

# Масштабируем только числовые переменные.
scaled_features = scaler.fit_transform(X.select_dtypes(include=[np.number]))

scaled_data = pd.DataFrame(scaled_features, index=X.index, columns=X.select_dtypes(include=[np.number]).columns)
# Не числовые данные нам не надо масштабировать, но они уже one-hot encoded, присоединим их к scaled_data
scaled_data = scaled_data.join(X.select_dtypes(exclude=[np.number]))

# Далее ваш код для разделения на обучающую и тестовую выборки и так далее.
scaler = StandardScaler()
scaler.fit(df.drop('credit_score', axis=1))
scaled_features = scaler.transform(df.drop('credit_score', axis=1))
scaled_data = pd.DataFrame(scaled_features, columns=df.drop('credit_score', axis=1).columns)

x = scaled_data
y = df['credit_score']

# Делим на обучающую и тестовую выборки
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=0)

# Тренируем модель
lr = LogisticRegressionCV(cv=3, random_state=0)
lr.fit(x_train, y_train)

from sklearn.metrics import precision_score, recall_score

y_pred_lr = lr.predict(x_test)

# Убедитесь, что ваши данные подходят под задачу классификации перед вычислением точности и полноты
precision_lr = precision_score(y_test, y_pred_lr, average='binary') # Для многоклассовой добавьте параметр average
recall_lr = recall_score(y_test, y_pred_lr, average='binary')       # Например, average='micro' или average='macro'

# Выводим результаты и видим, что модель работает нормально, но не идеально
print('LogisticRegressionCV: точность = {:.2f}, полнота = {:.2f}'.format(precision_lr, recall_lr))

print("Правильность на обучающем наборе: {:.2f}".format(lr.score(x_train, y_train)))
print("Правильность на тестовом наборе: {:.2f}".format(lr.score(x_test, y_test)))

LogisticRegressionCV: точность = 0.63, полнота = 0.44
Правильность на обучающем наборе: 0.76
Правильность на тестовом наборе: 0.76

In [36]:
df.to_csv('/credit_score_df.csv')

In [16]:
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score
import pandas as pd

# Предположим, у вас есть DataFrame с именем df
# Предполагается, что последний столбец 'df' является меткой класса
X = df.iloc[:, :-1].values  # матрица признаков (все данные кроме последнего столбца)
y = df.iloc[:, -1].values   # вектор меток классов (последний столбец)

# Разделение данных на обучающую и тестовую выборку
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

# Создание объекта классификатора
classifier = GaussianNB()

# Обучение классификатора на обучающих данных
classifier.fit(X_train, y_train)

# Предсказание меток классов на тестовых данных
y_pred = classifier.predict(X_test)

# Вычисление точности модели
accuracy = accuracy_score(y_test, y_pred)
print(f'Точность: {accuracy}')

Точность: 0.61915

In [55]:
import pandas as pd
from sklearn.model_selection import train_test_split
data = pd.DataFrame({'/credit_score_ds.csv'})
data.head()

                      0
0  /credit_score_ds.csv

In [88]:
# Предположим, у вас есть DataFrame с именем df
# Предполагается, что последний столбец 'df' является меткой класса
X = df.iloc[:, :-1].values  # матрица признаков (все данные кроме последнего столбца)
y = df.iloc[:, -1].values   # вектор меток классов (последний столбец)

df = pd.get_dummies(df)  # преобразовываем все категориальные переменные

# Разделение данных на обучающую и тестовую выборку
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=85)

from sklearn.ensemble import RandomForestClassifier

df_flattened = np.ravel(df)

clf = RandomForestClassifier(n_estimators=100)
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)

# Вычисление точности модели
accuracy = accuracy_score(y_test, y_pred)
print(f'Точность: {accuracy}')

Точность: 1.0

In [12]:
from sklearn.ensemble import RandomForestClassifier
import pandas as pd
import numpy as np

df = pd.read_csv('/content/credit_score_df.csv', sep = '|')
X = df.iloc[:, :-1].values

from sklearn.preprocessing import OneHotEncoder

# Предположим, что df - это ваш исходный DataFrame, и 'occupation' - это колонка для кодирования.
df_onehot = df.copy()

# Создаем экземпляр OneHotEncoder с параметром drop='first'
onehotencoder = OneHotEncoder(drop='first', sparse=False)

# Проводим one-hot кодирование, исключая первый признак, и создаем новый DataFrame
encoded_occupation = pd.DataFrame(onehotencoder.fit_transform(df_onehot[['occupation']]))

# Получаем новые имена для one-hot закодированных колонок, исключая первый признак
encoded_occupation.columns = onehotencoder.get_feature_names_out(['occupation'])

# Присоединяем закодированный DataFrame к исходному
df_onehot = df_onehot.join(encoded_occupation)

# Удаляем исходную колонку 'occupation'
df_onehot.drop('occupation', axis=1, inplace=True)

# Теперь df_onehot содержит закодированные признаки вместо исходной колонки 'occupation'
df_onehot

# Создаем массив данных
X = ['month',	'age',	'occupation',	'annual_income',	'monthly_inhand_salary',	'num_bank_accounts',	'num_credit_card',	'num_of_loan',	'num_credit_inquiries',	'credit_history_age',	'amount_invested_monthly',	'payment_behaviour',	'monthly_balance']
y_train = ['credit_score']
# Преобразуем массив данных в одномерный массив
X_flattened = np.ravel(X)

# Создаем объект RandomForestClassifier
clf = RandomForestClassifier(n_estimators=100)

# Обучаем модель на данных
clf.fit(X_flattened, y_train)

# Получаем значения важности признаков
feature_imp = pd.Series(clf.feature_importances_, X_flattened).sort_values(ascending=False)

# Используем iloc для доступа к отдельным значениям массива весов и создания Series на основе этих значений
feature_imp_reshaped = feature_imp.iloc[:, :].reshape(-1, 1)

# Выводим значения важности признаков
print(feature_imp_reshaped)

ValueError: ignored